name: Build and deploy to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build new Changes
        run: |
          npm i
          npm run build 
          ls
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Push Build
      - shell: bash
        env: 
          DISTRIBUTION_ID: ${{ secrets.distribution_id }}
        run: |
          aws s3 sync ./dist s3://damyn.me/
          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths /*
          
          
    
  

