name: Build and deploy to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build new Changes
        run: |
          npm i
          npm run build 
          ls 
          
    
  

